In [ ]:
"""
配列をつくる
様々な乱数の配列をつくる
配列を参照する
配列を操作する
配列の演算
その他応用
"""

In [29]:
"""
配列をつくる
"""
import numpy as np

### 配列をつくる
np.array([1, 2, 3])

### 要素がゼロの配列をつくる
np.zeros(3, dtype=float)

### aと同じ形式の、要素が同じゼロの行列をつくる
a = np.array([1, 2, 3])
np.zeros_like(a)

### 要素が1の配列をつくる
np.ones(3)

### 単位行列をつくる
np.eye(4)

### 規則的な配列をつくる
### (始点、終点（ただしアウトプットには含まれない）、間隔）
np.arange(0, 2, 0.5)

### 規則的な配列をつくる
### (始点、終点（アウトプットには含む）、個数）
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
"""
様々な乱数の配列をつくる
"""

### 0〜1の乱数を2つ作成
np.random.rand(2)

### 0〜1の乱数で2x2の行列を生成
np.random.rand(2, 2)

### 範囲での任意の整数の乱数を生成
### (始点、終点（ただしアウトプットには含まれない））
np.random.randint(1, 7)

### 平均0、分散1の標準正規分布に従う値を生成
np.random.randn()

### 平均0、分散1の標準正規分布に従う2x2の行列を生成
np.random.randn(2, 2)

### 正規分布の任意の平均・標準偏差を指定
np.random.normal(5, 1)

### 配列aの中からランダムに要素を抽出
a = np.array(10)
np.random.choice(a)

8

In [28]:
"""
配列の参照を行う
"""

### 行列の次元数を参照
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.ndim

### 行列の要素数を参照
a.size

### 行・列数を参照
a. shape

### 要素の型を参照
a.dtype

### 先頭を0番目とした際の1番目の値を参照
b = np.array([1, 2, 3])
b[1]

### 0番目から2番目の1つ手前までを参照
b[0:2]

### 0行1列目を参照
a[0,1]

### 1列目を参照
### コロンを用いてリストや文字列の一部を参照するのが、スライス
a[:,1]

### 1,2列目を参照
a[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [75]:
"""
配列を操作する
"""

### p行q列の配列に変換
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.reshape(3, 2)

### p行q列の配列に変換
### 変更された配列がもとの配列より大きければ、必要なだけ0で埋める
a.resize(3, 3)

### 多次元配列を1次元の行列にする
a.ravel()

### 配列の要素を反対にする
np.flip(a)

### スライスを利用して配列の要素を反対にする
a[::-1,::-1]

### 配列を転置
a.transpose()

### 配列の末尾に要素を追加
a = np.array([1, 2, 3])
np.append(a, 4)

### 配列の先頭に要素を追加
np.append(0, a)

### 条件を満たす要素のTrue・Falseを判定する
a = np.arange(6).reshape((2, 3))
np.where(a < 3, True, False)

### 条件を満たす要素を返す
np.where(a < 3)

### 配列の要素が全て条件を満たすか否かを判定
np.all(a < 3)

### 配列の要素のいずれかが条件を満たすか否かを判定
np.any(a > 6)

### 多次元配列の中の最大値の要素を持つインデックスを返す
a = np.array([1, 2, 3])
a.argmax()

### 配列を小さい順に並べ替える
np.sort(a)

### 配列を小さい順に並べ替えた際の配列のインデックスを出力
a = np.array([8, 2, 1, 5, 6])
np.argsort(a)

### 配列に次元を追加
a = np.arange(6).reshape(2, 3)
np.expand_dims(a, 0)

### 配列に次元を追加
np.expand_dims(a, 1)

### ブロードキャストと呼ばれる、異なる形状の配列を自動統一を実施
a = np.arange(2)
np.broadcast_to(a,(2, 2))

### 複数の配列をブロードキャストして形状を揃えたい際に使用する
a = np.arange(3)
b = np.arange(3).reshape(3, 1)
np.broadcast_arrays(a, b)

[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])]

In [105]:
"""
配列の演算
"""

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a)
print(b)

### 四則演算
print("四則演算の基本")
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

### 四則演算
print("四則演算の応用")
print(np.add(a, b))
print(np.subtract(a, b))

### 配列の要素の合計値
print("新規配列")
a = np.array([[1, 2, 3],[4,5,6]])
print(a)
print("要素の合計値")
print(np.sum(a))

### 列毎の合計値
print("列毎の合計値")
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

### アダマール積と、配列同士の積
print("いろいろな積")
print("新規配列")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("アダマール積＝要素ごとの積")
print(np.multiply(a,b))

print("配列同士の積")
print(np.dot(a,b))

### 平均、標準偏差、絶対値
print("各種統計量")
a = np.arange(10).reshape(2, 5)
print(np.mean(a))
print(np.std(a))

print("最大値")
print(np.max(a))
print("最小値")
print(np.min(a))

print(np.abs(a))

### 累乗、平方根、指数関数、対数関数
print("累乗と平方根")
print("2の3乗")
print(np.power(2, 3))

print("配列の各要素を2乗")
a = np.array([1, 2, 3])
print(np.power(a, 2))

print("平方根の計算")
print("4の平方根")
print(np.sqrt(4))

print("配列の各要素を平方根")
a = np.array([1, 4, 9])
print(np.sqrt(a))

print("eのx乗")
print(np.exp(1))
print(np.exp(a))

print("eを底とする対数")
print(np.log(2))
print(np.log(a))

### 三角関数
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[1 2 3]
[4 5 6]
四則演算の基本
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
四則演算の応用
[5 7 9]
[-3 -3 -3]
新規配列
[[1 2 3]
 [4 5 6]]
要素の合計値
21
列毎の合計値
[5 7 9]
[ 6 15]
いろいろな積
新規配列
アダマール積＝要素ごとの積
[ 4 10 18]
配列同士の積
32
各種統計量
4.5
2.8722813232690143
最大値
9
最小値
0
[[0 1 2 3 4]
 [5 6 7 8 9]]
累乗と平方根
2の3乗
8
配列の各要素を2乗
[1 4 9]
平方根の計算
4の平方根
2.0
配列の各要素を平方根
[1. 2. 3.]
eのx乗
2.718281828459045
[2.71828183e+00 5.45981500e+01 8.10308393e+03]
eを底とする対数
0.6931471805599453
[0.         1.38629436 2.19722458]
[ 0.84147098 -0.7568025   0.41211849]
[ 0.54030231 -0.65364362 -0.91113026]
[ 1.55740772  1.15782128 -0.45231566]


In [117]:
"""
その他応用
"""

print("新規配列")
a_1d = np.array([1, 2, 3, 4, 5, 6])
print(a_1d)
print("--------------------------")

print("累積和を取得")
print(np.cumsum(a_1d))
print("　データ型を指定可能")
print(np.cumsum(a_1d, dtype=float))
print("--------------------------")

print("多次元配列への応用")
a_2d = a_1d.reshape(2, 3)
print(a_2d)
print("--------------------------")

print("累積和を取得")
print(np.cumsum(a_2d))
print("※1次元に平坦化される")
print("")
print("列毎にはaxis=0, 行毎にはaxis=1を指定")
print(np.cumsum(a_2d, axis=0))
print(np.cumsum(a_2d, axis=1))
print("--------------------------")

print("累積和はcumsum, 累積積はcumprod")

新規配列
[1 2 3 4 5 6]
--------------------------
累積和を取得
[ 1  3  6 10 15 21]
　データ型を指定可能
[ 1.  3.  6. 10. 15. 21.]
--------------------------
多次元配列への応用
[[1 2 3]
 [4 5 6]]
--------------------------
累積和を取得
[ 1  3  6 10 15 21]
※1次元に平坦化される

列毎にはaxis=0, 行毎にはaxis=1を指定
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
--------------------------
累積和はcumsum, 累積積はcumprod
